;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-char
        evil-insert
        evil-mouse-drag-region
        evil-substitute
        helm-M-x
        helm-maybe-exit-minibuffer
        mc/mark-all-dwim-or-mark-sexp
        orgtbl-hijacker-command-109
        orgtbl-self-insert-command
        skk-insert
        ))

(setq mc/cmds-to-run-once
      '(
        evil-yank
        helm-smex
        skk-kakutei
        ))
